#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
    echo "🚀 Deploying to Raspberry Pi..."
    ./scripts/deploy.sh
else
    echo "Skipping deploy (not main)"
fi
